let shopItemsData = [
    {
        id: "asaddad",
        name: "Casual Shirt",
        price: 45,
        desc: "Lorem ipsum dolor sit amet consectetur casual shirt.",
        img: "images/img-1.jpg",
    },
    {
        id: "rthtjgh",
        name: "Office Shirt",
        price: 100,
        desc: "Lorem ipsum dolor sit amet office shirt.",
        img: "images/img-2.jpg",
    },
    {
        id: "axcvxcv",
        name: "T Shirt",
        price: 15,
        desc: "Lorem ipsum dolor sit amet consectetur t shirt.",
        img: "images/img-3.jpg",
    },
    {
        id: "sdgnvbtya",
        name: "Mens Suit",
        price: 285,
        desc: "lorem ipsum dolor sit amet god mens suit.",
        img: "images/img-4.jpg",
       },
   {
    id: "atttyyyu",
    name: "Mens Tie",
    price: 15,
    desc: "lorem ipsum dolor sit amet tie.",
    img: "images/img-5.jpg",
   },
   {
    id: "thtjtjtjt",
    name: "Casual Shoes",
    price: 175,
    desc: " Officiis, nulla.Lorem ipsum dolor  sit amet  casual shoes.",
    img: "images/img-6.jpg",
   },
   {
    id: "abnmhyyjy",
    name: "Black Suit",
    price: 415,
    desc: "lorem ipsum dolor sit amet black suit god.",
    img: "images/img-7.jpg",
   },
   {
    id: "bntrefff",
    name: "Polo Shirt",
    price: 35,
    desc: "lorem ipsum dolor sit amet polo shirt.",
    img: "images/img-8.jpg",
   },
   {
    id: "hfnmbtyaa",
    name: "Denim Shirt",
    price: 75,
    desc: " Officiis, nulla.Lorem ipsum dolor  sit amet denim pants.",
    img: "images/img-9.jpg",
   },
   {
    id: "basdadt",
    name: "Denim Pants",
    price: 115,
    desc: "lorem ipsum dolor sit amet denim pants.",
    img: "images/img-10.jpg",
   },
   {
    id: "tyuytghbdf",
    name: "Cap",
    price: 15,
    desc: "lorem ipsum dolor sit amet truck cap.",
    img: "images/img-11.jpg",
   },
   {
    id: "rsnaasgml",
    name: "Leather Boots",
    price: 335,
    desc: "lorem ipsum dolor sit amet winter leather boots.",
    img: "images/img-12.jpg",
   },
];